id: PBBD475B7
initial_creation_type: input
source_metadata:
  title: Getse Mahāpaṇḍita Series
  language: en
  description: 'Texts by and about Getse Mahāpaṇḍita Gyurme Tsewang Chokdrup (‘gyur
    med tshe dbang mchog grub, 1761–1829) of Katok:'
  volume:
    b175deeea9ed43d4b4e2901c93d3520b:
      title: 'Precise Discernment of Dharmas: A Catalogue of the Complete Collected
        Works of the Omniscient King of Dharma, Rigdzin Jigme Lingpa'
      parent: Catalogues
created_at: '2022-02-28T23:24:07.199630'
last_modified_at: '2022-02-28T23:24:07.199636'
